# Schema for the configuration files of the Customblock module.
customblock.settings:
  type: config_object
  label: 'Customblock settings'
  mapping:
    example:
      type: string
      label: 'Example'
