config_form.config:
  title: Config
  parent: system.admin_config_system
  route_name: config_form.config
  weight: 10

config_form.generate_otll:
  title: One Time Login Link of User
  parent: system.admin_config_system
  route_name: config_form.generate_otll
  weight: 11
