# Schema for the configuration files of the Config form module.
config_form.settings:
  type: config_object
  label: 'Config form settings'
  mapping:
    example:
      type: string
      label: 'Example'

# Schema for the configuration files of the Custom config form module.
config_form.generate_otll:
  type: config_object
  label: 'Custom Otl form settings'
  mapping:
    example:
      type: string
      label: 'Example'
