<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 * 
 * @param  array $form
 *   An associative array containing the structure of the form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 * @param string $form_id
 *   The id of the form.
 * 
 * @return void
 */
function customblock_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = 'customblock_user_login_form_submit';
}

/**
 * Custom submit handler for the login form. 
 * Redirects to front page after login.
 * 
 * @param  array $form
 *   An associative array containing the structure of the form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 * @param string $form_id
 *   The id of the form.
 * 
 * @return void
 */
function customblock_user_login_form_submit($form, FormStateInterface $form_state) {
  $form_state->setRedirect('<front>');
}
